<?php

use App\Http\Controllers\Api\AiInsightController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\ReportController;
use App\Http\Controllers\Api\SettingsController;
use App\Http\Controllers\Api\CustomerController;
use App\Http\Controllers\Api\LeadController;
use App\Http\Controllers\Api\SupplierController;
use App\Http\Controllers\Api\ProductCategoryController;
use App\Http\Controllers\Api\ProductController;
use App\Http\Controllers\Api\WarehouseController;
use App\Http\Controllers\Api\StockMovementController;
use App\Http\Controllers\Api\InvoiceController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Controllers\Api\PurchaseOrderController;
use App\Http\Controllers\Api\PurchaseInvoiceController;
use App\Http\Controllers\Api\EmployeeController;
use App\Http\Controllers\Api\AttendanceRecordController;
use App\Http\Controllers\Api\LeaveController;
use App\Http\Controllers\Api\PayrollController;
use App\Http\Controllers\Api\AccountController;
use App\Http\Controllers\Api\JournalEntryController;
use App\Http\Controllers\Api\ExpenseController;
use App\Http\Controllers\Api\CompanyController;
use App\Http\Controllers\Api\BranchController;
use App\Http\Controllers\Api\DepartmentController;
use App\Http\Controllers\Api\JobTitleController;
use App\Http\Controllers\Api\QuotationController;
use App\Http\Controllers\Api\SalesOrderController;
use App\Http\Controllers\Api\UnitController;
use Illuminate\Support\Facades\Route;

Route::prefix('auth')->group(function () {
    Route::post('login', [AuthController::class, 'login'])->middleware('throttle:10,1');
    Route::post('register', [AuthController::class, 'register'])->middleware('throttle:6,1');
    Route::post('forgot-password', [AuthController::class, 'forgotPassword']);
    Route::post('reset-password', [AuthController::class, 'resetPassword']);
});

Route::middleware('auth:sanctum')->group(function () {
    Route::get('auth/me', [AuthController::class, 'me']);
    Route::put('auth/profile', [AuthController::class, 'updateProfile']);
    Route::put('auth/change-password', [AuthController::class, 'changePassword']);
    Route::post('auth/logout', [AuthController::class, 'logout']);
    Route::get('dashboard/summary', [DashboardController::class, 'summary']);
    Route::get('reports/sales', [ReportController::class, 'sales']);
    Route::get('reports/purchases', [ReportController::class, 'purchases']);
    Route::get('reports/inventory', [ReportController::class, 'inventory']);
    Route::get('reports/profit-loss', [ReportController::class, 'profitLoss']);
    Route::get('ai/insights', [AiInsightController::class, 'insights']);
    Route::post('ai/analyze', [AiInsightController::class, 'analyze']);
    Route::get('settings', [SettingsController::class, 'index']);
    Route::put('settings', [SettingsController::class, 'update']);
    Route::apiResource('customers', CustomerController::class);
    Route::apiResource('leads', LeadController::class);
    Route::apiResource('suppliers', SupplierController::class);
    Route::apiResource('categories', ProductCategoryController::class);
    Route::apiResource('products', ProductController::class);
    Route::apiResource('warehouses', WarehouseController::class);
    Route::apiResource('stock-movements', StockMovementController::class);
    Route::apiResource('invoices', InvoiceController::class);
    Route::apiResource('payments', PaymentController::class);
    Route::apiResource('purchase-orders', PurchaseOrderController::class);
    Route::apiResource('purchase-invoices', PurchaseInvoiceController::class);
    Route::apiResource('employees', EmployeeController::class);
    Route::apiResource('attendance', AttendanceRecordController::class);
    Route::apiResource('leaves', LeaveController::class);
    Route::apiResource('payrolls', PayrollController::class);
    Route::apiResource('accounts', AccountController::class);
    Route::apiResource('journal-entries', JournalEntryController::class);
    Route::apiResource('expenses', ExpenseController::class);
    Route::apiResource('companies', CompanyController::class);
    Route::apiResource('branches', BranchController::class);
    Route::apiResource('departments', DepartmentController::class);
    Route::apiResource('job-titles', JobTitleController::class);
    Route::apiResource('quotations', QuotationController::class);
    Route::apiResource('sales-orders', SalesOrderController::class);
    Route::apiResource('units', UnitController::class);
});
